### ISSUE TITLE
Broken links on IBM Cloud 

### ISSUE THREAD

**Issue by rodalton** [IBM-Bluemix-Docs/SecureGateway#14]
Number of links are broken e.g. Requirements to run on the client points to https://console.bluemix.net/docs/securegateway_requirements.html#requirements-to-run-the-client

Should be https://console.bluemix.net/docs/services/SecureGateway/securegateway_requirements.html

**Comment by ceciliachoi** [comment]
Hello
We've fixed it with change https://github.com/IBM-Bluemix-Docs/SecureGateway/commit/0c58137b33d494fd6f473b331efada8b5a881dad
Thank you.
