### ISSUE TITLE
Add a FAQ?

### ISSUE THREAD

**Issue by edludke** [IBM-Bluemix-Docs/SecureGateway#19]
Forgive me if this is not the right place, but had a question asked of me that I thought would be very helpful in the FAQs.

What can/should be done to avoid having a single point of failure and/or being able to handle high volumes with the SecureGateway Client (SGC)? For example, can they still function behind a local load balancer with a VIP? How does that affect/work with bi-directional support?

&ast;edit&ast;
I wanted to add some detail. I've seen how resiliency/redundancy is achieved by having more than one client on-prem - but that seems to only help with calls _into_ the Secure Gateway Server (which will do the load balancing) via clients to an on-prem resource.  But according to this: "_The new cloud destination allows an on-premises service/application to send information/requests to a cloud application **via the Secure Gateway Client**_" (found here: https://console.bluemix.net/docs/services/SecureGateway/securegateway_about.html#about-secure-gateway) you can initiate calls via the SGC? How would those calls be load balanced? Is that where a local load balancer would be required (and would that work)? 

Hopefully you see why this might make a great FAQ entry....

**Comment by ceciliachoi** [comment]
Hello
Sorry for the late response.
We only support HA for on-premises destination connections.
Updated the document with change https://github.com/IBM-Bluemix-Docs/SecureGateway/commit/b01521cdc72e5f4472b96b921bef049eb093e150
Thank you.

**Comment by edludke** [comment]
No worries - a slow response is better than no response ;-). The information is still very helpful. Thanks!

**Comment by ceciliachoi** [comment]
@edludke 
If you have questions next time:
For internal customer, please ask in the Slack channel #securegateway 
For external customer, please create the ticket in the normal [IBM cloud ticketing system](https://cloud.ibm.com/unifiedsupport/supportcenter).
Thank you.
