### ISSUE TITLE
What is a dedicated IP ? 

### ISSUE THREAD

**Issue by mwilcox12015** [IBM-Bluemix-Docs/SecureGateway#23]
Can we document what the dedicated IP offers to us ?

**Comment by ceciliachoi** [comment]
Hello
Sorry for the late response.
Updated the document with change https://github.com/IBM-Bluemix-Docs/SecureGateway/commit/b88daaeae9c19c742a8cfe4f9e6d35e1ba87fcd0
Thank you.
